import type { Metadata } from "next";
import { Comic_Neue } from "next/font/google";
import "./globals.css";

const inter = Comic_Neue({ weight: ["400"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Nicis Geiler Adventskalender",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="de">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
